### ISSUE TITLE
Error message: 'dict object' has no attribute 'release_date'

### ISSUE THREAD

**Issue by drphilmarshall** [lsst-sqre/lsst-technote-bootstrap#6]
@jonathansick I'm trying out your technote startup script, and hit the problem below. Any ideas what went wrong?

> pjm@PPA-PC92478 > cookiecutter https://github.com/lsst-sqre/lsst-technote-bootstrap.git
> Cloning into 'lsst-technote-bootstrap'...
> remote: Counting objects: 119, done.
> remote: Total 119 (delta 0), reused 0 (delta 0), pack-reused 119
> Receiving objects: 100% (119/119), 31.73 KiB | 0 bytes/s, done.
> Resolving deltas: 100% (62/62), done.
> Checking connectivity... done.
> first_author [First Last]: Phil Marshall
> Select series:
> 1 - SQR
> 2 - DMTN
> 3 - SMTN
> Choose from 1, 2, 3 [1]: 2
> serial_number [000]: 037
> title [Document Title]: DESC Notes: Guidelines for Authors
> repo_name [dmtn-037]: descnotes-037
> Select github_org:
> 1 - lsst-sqre
> 2 - lsst-dm
> 3 - lsst-sims
> Choose from 1, 2, 3 [1]: 2
> github_namespace [lsst-dm/descnotes-037]: 
> docushare_url []: 
> url [http://dmtn-037.lsst.io]: 
> description [A short description of this document]: A short description would go here.
> copyright_year [2016]: 
> copyright_holder [AURA/LSST]: LSST DESC
> Unable to create file 'metadata.yaml'
> Error message: 'dict object' has no attribute 'release_date'
> Context: {
>     "cookiecutter": {
>         "copyright_holder": "LSST DESC", 
>         "copyright_year": "2016", 
>         "description": "A short description would go here.", 
>         "docushare_url": "", 
>         "first_author": "Phil Marshall", 
>         "github_namespace": "lsst-dm/descnotes-037", 
>         "github_org": "lsst-dm", 
>         "repo_name": "descnotes-037", 
>         "serial_number": "037", 
>         "series": "DMTN", 
>         "title": "DESC Notes: Guidelines for Authors", 
>         "url": "http://dmtn-037.lsst.io"
>     }
> }

**Comment by jonathansick** [comment]
Sorry @drphilmarshall that came from a recent change; by default we now get the date from git history. I just pushed a fix for your problem.

**Comment by drphilmarshall** [comment]
Got it - thanks Jonathan! :-)
